/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author linoe
 */
public class joystick extends javax.swing.JPanel {

    /**
     * Creates new form joystick
     */
    public joystick() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleright = new javax.swing.JToggleButton();
        jToggleLeft = new javax.swing.JToggleButton();
        jToggleLeft1 = new javax.swing.JToggleButton();
        jToggleright1 = new javax.swing.JToggleButton();

        jToggleright.setText(">");

        jToggleLeft.setText("<");
        jToggleLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleLeftActionPerformed(evt);
            }
        });

        jToggleLeft1.setText("<");
        jToggleLeft1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleLeft1ActionPerformed(evt);
            }
        });

        jToggleright1.setText(">");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jToggleLeft)
                .addGap(68, 68, 68)
                .addComponent(jToggleright)
                .addContainerGap(199, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleLeft1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleright1)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleLeft1)
                    .addComponent(jToggleright1))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleLeft)
                    .addComponent(jToggleright))
                .addContainerGap(159, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleLeftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleLeftActionPerformed

    private void jToggleLeft1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleLeft1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleLeft1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jToggleLeft;
    private javax.swing.JToggleButton jToggleLeft1;
    private javax.swing.JToggleButton jToggleright;
    private javax.swing.JToggleButton jToggleright1;
    // End of variables declaration//GEN-END:variables
}
