/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import backend.interactions;

import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.text.BadLocationException;


/**
 *
 * @author linoe
 */
public class mainGUI extends javax.swing.JFrame {

    /**
     * Creates new form mainGUI
     */
    interactions _inter;
    public mainGUI() {
        initComponents();
        
    }
    public void begin(interactions inter) {
        this._inter = inter;
    
            
        this.setVisible(true);
        
        //add some useful things
        
        (new Thread(){
            public void run(){
                while(true){
                    
                    try {
                        if(_inter.is_moving_up()){
                            jToggle_up.setSelected(true);
                        } else {
                            jToggle_up.setSelected(false);
                        }
                        
                        if(_inter.is_moving_down()){
                            jToggle_down.setSelected(true);
                            
                        } else {
                            jToggle_down.setSelected(false);
                            
                        }
                        
                        if(_inter.is_moving_left()){
                            jToggle_left.setSelected(true);
                        } else {
                            jToggle_left.setSelected(false);
                        }
                        
                        if(_inter.is_moving_right()){
                            jToggle_right.setSelected(true);
                        } else {
                            jToggle_right.setSelected(false);
                        }
                        
                        if(_inter.is_moving_inside()){
                            jToggle_in.setSelected(true);
                        } else {
                            jToggle_in.setSelected(false);
                        }
                        
                        if(_inter.is_moving_outside()){
                            jToggle_out.setSelected(true);
                        } else {
                            jToggle_out.setSelected(false);
                        }
                        if(!_inter.isCalibrated){
                            jToggle_up.setEnabled(false);
                            jToggle_down.setEnabled(false);
                            jToggle_left.setEnabled(false);
                            jToggle_right.setEnabled(false);
                        }
                        Thread.sleep(10);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(mainGUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            
            }
            
        }).start();
        
    }
    
    public void log(String message){
        this.jText_log.append(message + "\n");
        try {
            this.jText_log.setCaretPosition(jText_log.getLineStartOffset(jText_log.getLineCount() - 1));
        } catch (BadLocationException ex) {
            Logger.getLogger(mainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jText_log = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jToggle_up = new javax.swing.JToggleButton();
        jToggle_left = new javax.swing.JToggleButton();
        jToggle_right = new javax.swing.JToggleButton();
        jToggle_down = new javax.swing.JToggleButton();
        jToggle_in = new javax.swing.JToggleButton();
        jToggle_out = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STR LABWORK2");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(500, 400));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jText_log.setColumns(20);
        jText_log.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jText_log.setRows(5);
        jScrollPane2.setViewportView(jText_log);

        jLabel1.setText("log");

        jToggle_up.setText("▲");
        jToggle_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggle_upActionPerformed(evt);
            }
        });

        jToggle_left.setText("◄");
        jToggle_left.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggle_leftActionPerformed(evt);
            }
        });

        jToggle_right.setText("►");
        jToggle_right.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggle_rightActionPerformed(evt);
            }
        });

        jToggle_down.setText("▼");
        jToggle_down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggle_downActionPerformed(evt);
            }
        });

        jToggle_in.setText("◄");
        jToggle_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggle_inActionPerformed(evt);
            }
        });

        jToggle_out.setText("►");
        jToggle_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggle_outActionPerformed(evt);
            }
        });

        jLabel2.setText("Joystick");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jToggle_down, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jToggle_up, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                                .add(jToggle_left)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jToggle_right)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jToggle_in)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jToggle_out)))
                .add(0, 10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jToggle_up)
                    .add(jToggle_in)
                    .add(jToggle_out))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jToggle_left)
                    .add(jToggle_right))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jToggle_down))
        );

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 239, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 66, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        jButton1.setText("3,1");

        jButton2.setText("3,2");

        jButton3.setText("3,3");

        jButton4.setText("2,3");

        jButton5.setText("2,2");

        jButton6.setText("2,1");

        jButton7.setText("1,3");

        jButton8.setText("1,2");

        jButton9.setText("1,1");

        jToggleButton1.setText("goTo");

        jToggleButton2.setText("PutPiece");

        jToggleButton3.setText("getPiece");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jToggleButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 157, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jButton1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton3))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jButton6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton4))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jButton9)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton8)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton7))
                    .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jToggleButton2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jToggleButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(58, 58, 58)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jButton2)
                    .add(jButton3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton6)
                    .add(jButton5)
                    .add(jButton4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton9)
                    .add(jButton8)
                    .add(jButton7))
                .add(18, 18, 18)
                .add(jToggleButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jToggleButton2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jToggleButton3)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggle_leftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggle_leftActionPerformed
        // TODO add your handling code here:
        if(this.jToggle_left.isSelected())
            _inter.move_x_left();
        else 
            _inter.stop_x();
        
    }//GEN-LAST:event_jToggle_leftActionPerformed

    private void jToggle_rightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggle_rightActionPerformed
        // TODO add your handling code here:
        if(this.jToggle_right.isSelected())
            _inter.move_x_right();
        else 
            _inter.stop_x();
    }//GEN-LAST:event_jToggle_rightActionPerformed

    private void jToggle_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggle_upActionPerformed
        // TODO add your handling code here:
        if(this.jToggle_up.isSelected())
            _inter.move_z_up();
        else 
            _inter.stop_z();
    }//GEN-LAST:event_jToggle_upActionPerformed

    private void jToggle_downActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggle_downActionPerformed
        // TODO add your handling code here:
        if(this.jToggle_down.isSelected())
            _inter.move_z_down();
        else 
            _inter.stop_z();
    }//GEN-LAST:event_jToggle_downActionPerformed

    private void jToggle_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggle_inActionPerformed
        // TODO add your handling code here:
        if(this.jToggle_down.isSelected())
            _inter.move_y_inside();
        else 
            _inter.stop_y();
    }//GEN-LAST:event_jToggle_inActionPerformed

    private void jToggle_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggle_outActionPerformed
        // TODO add your handling code here:
        if(this.jToggle_down.isSelected())
            _inter.move_y_outside();
        else 
            _inter.stop_y();
    }//GEN-LAST:event_jToggle_outActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
            try {
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(mainGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(mainGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(mainGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(mainGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jText_log;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggle_down;
    private javax.swing.JToggleButton jToggle_in;
    private javax.swing.JToggleButton jToggle_left;
    private javax.swing.JToggleButton jToggle_out;
    private javax.swing.JToggleButton jToggle_right;
    private javax.swing.JToggleButton jToggle_up;
    // End of variables declaration//GEN-END:variables

    
}
